version: '3.6'
services:

  noodle-pg:
    container_name: noodle-pg
    image: postgres:9.6.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: noodle

  noodle-backend:
    container_name: noodle-backend
    build:
      context: .
      dockerfile: .dockerfile
    ports:
      - 8080:8080
    image: noodle-backend
    volumes:
      - ./config:/usr/app/config
    environment:
      - NODE_ENV=dev-docker
    command: npm start
    links:
      - noodle-pg

  noodle-swagger:
    container_name: noodle-swagger
    image: swaggerapi/swagger-ui
    ports:
      - 8081:8080
    environment:
      - SWAGGER_JSON=/swagger/noodle-mvp-rest-api-swagger.yaml
    volumes:
      - ./swagger:/swagger
    links:
      - noodle-backend
      # todo: find out how to make noodle-backend host visible for swagger on html-page

networks:
  default:
    name: noodle-network
