version: '3.6'
services:

  noodle-pg-test:
    container_name: noodle-pg-test
    image: postgres:9.6.5
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: noodle-test

  noodle-integration-testing:
    container_name: noodle-integration-testing
    build:
      context: .
      dockerfile: .dockerfile
    ports:
      - 8082:8082
    image: noodle-integration-testing
    volumes:
      - ./config:/usr/app/config
    environment:
      - NODE_ENV=test-docker
    command: npm run test
    links:
      - noodle-pg-test

networks:
  default:
    name: noodle-test-network
