db:
  host: localhost
  port: 5433
  database: noodle-test
  user: user
  password: password
  minConnections: 1
  maxConnections: 20
http:
  port: 8082
jwt:
  expiresIn: 10d
  secret: jhprouwy7345ythfeldgjae3h4utqhkuqwi4t73y4uthq3i4utyi7hkgakeuh4it73h4iq
