db:
  host: localhost
  port: 5432
  database: noodle
  user: user
  password: password
  min-connections: 1
  max-connections: 20
http:
  port: 8080
jwt:
  expires-in: 10d
  secret: akljsd;kfjalkjerpigjcnsjbhapukehrghw[oi5tjhg987dye857y4uahgjfdhagpkhe4hu
